services:
  postgres-development:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis-development:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  
  rabbitmq-development:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq


# TOOLS

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      # opcional: habilitar persistência, telemetria, etc
      - IS_PERSISTENT=true
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped